// Investment Decision Dashboard Types

export type LightStatus = 'green' | 'yellow' | 'red';
export type RegimeType = 'A' | 'B' | 'C' | 'D';
export type ActionType = 'ADD' | 'REDUCE' | 'HOLD';
export type AssetType = 'crypto' | 'equity' | 'hk_equity' | 'metal' | 'future';

export interface MacroIndicator {
  id: string;
  name: string;
  value: number;
  change7d: number;
  change1m: number;
  percentile: number;
  light: LightStatus;
  freshness: number; // days
  frequency: 'D' | 'W' | 'M';
  source: string;
}

export interface Asset {
  id: string;
  name: string;
  ticker: string;
  assetType: AssetType;
  currency: string;
  benchmarkId?: string;
  baseMaxWeight: number;
  currentWeight: number;
  suggestedMaxWeight: number;
  price: number;
  priceChange24h: number;
  priceChange7d: number;
  priceChange30d: number;
}

export interface AssetSignal {
  assetId: string;
  date: string;
  trendLight: LightStatus;
  riskLight: LightStatus;
  catalystLight: LightStatus;
  suggestedMaxWeight: number;
  action: ActionType;
  reasonCodes: string[];
  notes: string;
}

export interface AssetTechnicalData {
  assetId: string;
  ma20: number;
  ma60: number;
  ma200: number;
  mom12w: number;
  rsToBenchmark: number;
  vol20Ann: number;
  mdd60: number;
  mdd120: number;
  volPercentile1y: number;
  ddPercentile1y: number;
  correlationDXY: number;
  correlationRealRate: number;
  correlationSPX: number;
}

export interface DailySignal {
  date: string;
  regime: RegimeType;
  riskScore: number;
  drivers: string[];
  portfolioAction: ActionType;
  riskMode: string;
  aiDiffusionIndex: number;
  constraintIndex: number;
  commentSummary: string;
  dataAsOf: string;
}

export interface MacroSwitch {
  id: string;
  name: string;
  currentValue: number;
  change7d: number;
  change1m: number;
  percentile: number;
  light: LightStatus;
  freshness: number;
  frequency: 'D' | 'W' | 'M';
}

export interface PriceData {
  date: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}

export interface WeeklyKondratieff {
  date: string;
  aiDiffusionIndex: number;
  constraintIndex: number;
  phase: 'spring' | 'winter' | 'transition';
  strategy: string;
  components: {
    soxRatio: number;
    nvdaRatio: number;
    utilityRatio: number;
    copperMomentum: number;
    energyPrice: number;
  };
}

export interface PortfolioPosition {
  assetId: string;
  currentWeight: number;
  targetWeight: number;
  allowedAddSpace: number;
  needReduce: number;
}

export interface DashboardState {
  selectedDate: string;
  selectedAssetId: string | null;
  currentView: 'daily' | 'asset' | 'weekly';
}

/**
 * Payload schema for /public/data/dashboard.json
 * (generated by your agent).
 */
export interface DashboardPayload {
  version?: string;
  generatedAt?: string;
  dailySignal: DailySignal;
  macroSwitches: MacroSwitch[];
  assets: Asset[];
  assetSignals: AssetSignal[];
  weeklyKondratieff?: WeeklyKondratieff;
  technicalData?: Record<string, AssetTechnicalData>;
  priceHistory?: Record<string, PriceData[]>;
}
